# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

def configure(conf):
#    conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')
    conf.env['ENABLE_nckernel']=conf.check(mandatory=True,
    libpath=['/usr/local/lib'],
    includes=['/home/kai/repos/nckernel/build/include/nckernel/'],
    lib='nckernel',uselib_store='LIB_NCKERNEL')
def build(bld):
    obj = bld.create_ns3_program('platooning-example', ['platooning'])
    obj.source = 'platooning.cc'
    obj.use.append("LIB_NCKERNEL")

    # bld.ns3_python_bindings()
